### ISSUE TITLE
Non-Collapsing Sub-Grid Columns

### ISSUE THREAD

**Issue by dhenry-adpear** [foundation/foundation-emails#24]
Is there a reason that there wasn't the CSS included for the Non-Collapsing Sub-Grid Columns within the download? I kept getting the columns 100% width overriding my columns. However it is shown in the documentation (http://zurb.com/ink/docs.php). After digging a little bit through the code I found the CSS that was missing to make those function properly. After inserting it things seem to work fine. Just curious.

``` CSS
.body .columns td.one,
.body .column td.one, { width: 8.333333% !important; }
.body .columns td.two,
.body .column td.two { width: 16.666666% !important; }
.body .columns td.three,
.body .column td.three { width: 25% !important; }
.body .columns td.four,
.body .column td.four { width: 33.333333% !important; }
.body .columns td.five,
.body .column td.five { width: 41.666666% !important; }
.body .columns td.six,
.body .column td.six { width: 50% !important; }
.body .columns td.seven,
.body .column td.seven { width: 58.333333% !important; }
.body .columns td.eight,
.body .column td.eight { width: 66.666666% !important; }
.body .columns td.nine,
.body .column td.nine { width: 75% !important; }
.body .columns td.ten,
.body .column td.ten { width: 83.333333% !important; }
.body .columns td.eleven,
.body .column td.eleven { width: 91.666666% !important; }
.body .columns td.twelve,
.body .column td.twelve { width: 100% !important; }
```
