### ISSUE TITLE
@font-face definitions don't get embedded into HTML build

### ISSUE THREAD

**Issue by jsit** [foundation/foundation-emails#284]
`$ foundation new --framework emails`

`$ npm run build`

``` scss
// src/assets/scss/app.scss

@import 'settings';
@import 'foundation';

@font-face {
  font-family: 'Franklin Gothic';
  src: url("https://example.com/Franklin-Gothic.woff") format("woff");
}
```

The `@font-face` definition doesn't get embedded in the HTML build, so an element with `font-face:"Franklin Gothic";` won't be rendered in Franklin Gothic.
