### ISSUE TITLE
$button-border not declared as value in _button.scss

### ISSUE THREAD

**Issue by ghost** [foundation/foundation-emails#339]
Seems like I can't style the border of a button through _settings.scss.

This is declared in _button.scss:

``` css
table.button {
  table {
    td {
      border: 2px solid $button-background;
     }
   }
 }
```

But shouldn't that be like this:

``` css
table.button {
  table {
    td {
      border: $button-border;
     }
   }
 }
```
