### ISSUE TITLE
Are button hover states working?

### ISSUE THREAD

**Issue by iamsankalp** [foundation/foundation-emails#437]
Button hover states don't seem to be working for me. Checked in browser, Apple Mail and Gmail. Most of the buttons in my layout are via the following code block.

```
<row>
    <columns>
      <center>
        <button href="#" class="radius">Track order status</button>
      </center>
    </columns>
</row>
```

Please let me know, what more info i can give to help with this... Thanks!

**Comment by cossssmin** [comment]
Checking the HTML being output, it looks like the compiler ignores any CSS rules that have the `:hover` pseudo-selector in them - these don't make it in the `<style>`

However, something like `:first-child` works...

So for now, you'd need to manually add them. Don't forget `!important`, since the `<a>` elements have color defined inline.

**Comment by rafibomb** [comment]
Assuming you are referring to inlined code right? The hover states seem to work in development.

**Comment by rafibomb** [comment]
Looks like the inliner is the issue here: https://github.com/jonkemp/inline-css/issues/31

The maintainer may need some help in the form of a PR on it...

**Comment by samumist** [comment]
button `:hover` state works in development but not in production.

**Comment by rafibomb** [comment]
Yeah - It's definitely the inliner. One option is to rip the inliner out all together because with the Gmail responsive update it's no longer needed. Issue with that is right now IOS Gmail app didn't get the update: https://litmus.com/blog/gmail-to-support-responsive-email-design

Other option is to decouple the inline task from the build allowing us to run a task to ignore certain things it's messing with.

Or - we can get inliner maintainer to update the inliner.

**Comment by jeremy1reynolds** [comment]
I think I just found a workaround in the inliner's parent lib issue queue: Automattic/juice#237.

Media queries don't strip pseudos, so the workaround is to wrap everything in an `all` rule:

```css
@media all {
// typography
  a:hover { color: $anchor-color-hover }
  a:active { color: $anchor-color-active }
  a:visited { color: $anchor-color-visited }
// buttons
  table.button:hover, table.button:visited, table.button:active {
    table a { border-width: 0px }
    table td {
      background: darken($button-background, 10%) !important;
      color: $button-color !important;
    }
  }
  table.button.secondary:hover table td {
    background: lighten($secondary-color, 10%) !important
  }
  table.button.success:hover table td {
    background: darken($success-color, 10%) !important
  }
  table.button.alert:hover table td {
    background: darken($alert-color, 10%) !important
  }
  table.button.warning:hover table td {
    background: darken($warning-color, 10%) !important
  }
}
```

Haven't run it through litmus, but it works in browser and (I assume) should work on any email clients that respect media queries.
