### ISSUE TITLE
iOS Blue links for dates and times

### ISSUE THREAD

**Issue by zurbrandon** [foundation/foundation-emails#442]
**How can we reproduce this bug?**
Dates and times on iOS become hidious blue regardless of the base link color. Let's fix that :) 

This article has a great snippet in it that prevents that, can we do this or something similar by default in F4E? 

http://blog.emailwizardry.co/2016/04/the-absolute-easiest-way-to-beat-blue-links-in-emails-on-ios/

**Comment by davidhouweling** [comment]
Encountered the same issue. Unfortunately I don't think this is an issue with foundation-emails but rather that a helper should be provided.

I created this helper...

``` scss
// iOS hack to ensure its 'smart' linking doesn't mess our styles
@media only screen {
  .unlink {
    a {
      color: inherit;
      text-decoration: inherit;
    }
  }
}
```

Then on the container element of the text that is causing the problem, simply add a class `unlink` and it will take care of the rest.

For example... `<span class="time">09:00</span>` will become `<span class="time unlink">09:00</span>`. The great advantage of this approach is that if you've got large blocks of text that you don't want styled, it works on that as well. This is needed for things such as addresses, 'Today', dates, times, websites without links (your brand might be SomeBrand.com but don't want to link it for some reason).
