### ISSUE TITLE
Using collapse doesn't seem to set the correct width on first and last cells

### ISSUE THREAD

**Issue by codedbypaul** [foundation/foundation-emails#456]
**How can we reproduce this bug?**

```
<row class="collapse">
   <columns small="12" large="4">
      <img src="assets/img/image1.jpg" />
      <h3>One Word</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<br>
      <a href="#">Read more</a></p>
   </columns>
   <columns small="12" large="4">
      <img src="assets/img/image2.jpg" />
      <h3>One Word</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<br>
      <a href="#">Read more</a></p>
   </columns>
   <columns small="12" large="4">
      <img src="assets/img/image3.jpg" />
      <h3>One Word</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<br>
      <a href="#">Read more</a></p>
   </columns>
</row>
```

**What did you expect to happen?**

![expected](https://cloud.githubusercontent.com/assets/4680439/15752961/7340d4e2-28e8-11e6-9dd1-3ac314eda5b3.jpg)

**What happened instead?**

![actual](https://cloud.githubusercontent.com/assets/4680439/15752966/7ac7f15a-28e8-11e6-8540-7f887d6f78b9.jpg)

**What email clients does this happen in?**

Only testing locally at the moment.

**Comment by codedbypaul** [comment]
I have my global width set to 600px. I was expecting 3 columns to be 200px each. For some reason .first and .last are given a width of 208px.

**Comment by rafibomb** [comment]
Does this happen with the default global width?

**Comment by rafibomb** [comment]
@codedbypaul We're looking to narrow down how/when it's happening. Do you see this with different container widths including the default width? Can you see if changing that affect it's greater or less?

**Comment by keokilee** [comment]
We're seeing it on the default container width, but only at the large breakpoint. When it switches to small, the column widths all match.

**Comment by axelson** [comment]
Does anyone have a work-around for this?

**Comment by evanre** [comment]
File _grid.scss:
```scss
  //Collapsed logic
  .collapse {
    > tbody > tr > td.large-#{$i},
    > tbody > tr > th.large-#{$i} {
      padding-right: 0;
      padding-left: 0;
      width: -zf-grid-calc-px($i, $grid-column-count, $global-width) + $global-gutter;
    }

    //Gotta give it that extra love for the first and last columns.
    td.large-#{$i}.first,
    th.large-#{$i}.first,
    td.large-#{$i}.last,
    th.large-#{$i}.last {
      width: -zf-grid-calc-px($i, $grid-column-count, $global-width) + ($global-gutter * 1.5);
    }
  }
````
For what purpose was added this 1.5 multiplier for .first/.last columns? - 
`($global-gutter * 1.5)`
