### ISSUE TITLE
Percentage columns in the container

### ISSUE THREAD

**Issue by ivanov-v** [foundation/foundation-emails#511]
When I put the container in a container inside a column having a width in percent without indents.
I need to maintain paddings.

```
<container>
  <row>
    <columns>
      <container>
        <row>
          <columns>1</columns>
          <columns>2</columns>
          <columns>3</columns>
        </row>
      </container>
    </columns>
  </row>
</container>
```

Now template.
![2016-07-06 13 38 36](https://cloud.githubusercontent.com/assets/13759065/16615385/f9cd8770-437e-11e6-8265-84ba7a997439.png)

**Comment by rafibomb** [comment]
Not sure what the issue is here, can explain what is happening vs what you expected to happen? I don't think the containers were meant to be nested.

**Comment by ivanov-v** [comment]
I was expecting normal behavior of columns. In the current structure of the columns disappear paddings.
To put the container in a container is forbidden?

**Comment by sergeylukin** [comment]
OP has contacted me directly and has explained the issue. I decided to assist and here is my interpretation of the question: how to nest components inside components without losing the padding (which is overwritten by `.columns .columns { padding-left: 0; padding-right: 0; }` and such.

@dynamitegit my suggestion would be to assign a class to inner block and overwrite the default padding reset, like so (insert that in, say, `<Foundation Template path>/src/pages/demo.html`:

``` html
---
subject: My Email Subject
---
<style>
.Header .columns {
  padding-bottom: 0;
}

.Header .wrapper-inner {
  padding: 20px;
}

.Header .container {
  background: #CEDBEB;
}

.Block {
  border-width: 1px;
  border-style: solid;
  border-color: grey;
  border-radius: 5px;
  display: block !important;
}
th.columns .Block-column,
td.columns .Block-column {
  padding-top: 16px;
  padding-right: 16px !important;
  padding-bottom: 16px;
  padding-left: 16px !important;
}
@media only screen and (max-width: 596px) {
  th.columns .Block-column,
  td.columns .Block-column,
  table.body .columns .Block-column {
    padding-top: 16px;
    padding-right: 16px !important;
    padding-bottom: 16px;
    padding-left: 16px !important;
  }
}

.u-marginBn {
  margin-bottom: 0 !important;
}
</style>
<wrapper class="Header">
  <container>
    <row class="collapse">
      <columns large="6"><img src="http://placekitten.com/100/50" class="small-float-center" /></columns>
      <columns large="6" valign="middle"><p class="small-text-center text-right u-marginBn">Address</p></columns>
    </row>
  </container>
</wrapper>
<container>
  <row>
    <columns small="12" large="12">
      <h1>Hello</h1>
      <p>Foo bar</p>
    </columns>
  </row>
  <row>
    <columns>
      <row class="Block">
        <columns class="Block-column">
          <row>
            <columns>
              <row>
                <columns>
                  <h2>News</h2>
                </columns>
              </row>
              <row>
                <columns large="8">
                  <row>
                    <columns>01.01.2017</columns>
                  </row>
                  <row>
                    <columns>
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure
                        perferendis praesentium quia distinctio, assumenda dolor pariatur!</p>
                    </columns>
                  </row>
                </columns>
                <columns large="4" class="show-for-large">
                  <img src="http://placekitten.com/200/100" />
                </columns>
              </row>
            </columns>
          </row>
          <row>
            <columns>
              <row>
                <columns large="8">
                  <row>
                    <columns>01.01.2017</columns>
                  </row>
                  <row>
                    <columns>
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure
                        perferendis praesentium quia distinctio, assumenda dolor pariatur!</p>
                    </columns>
                  </row>
                </columns>
                <columns large="4" class="show-for-large">
                  <img src="http://placekitten.com/200/100" />
                </columns>
              </row>
            </columns>
          </row>
        </columns>
      </row>
    </columns>
  </row>
</container>
```

which results in:

<img width="887" alt="screen shot 2016-07-06 at 11 45 11 pm" src="https://cloud.githubusercontent.com/assets/720339/16633835/c9083ea0-43d3-11e6-875e-c5829f237d93.png">

and following for small screens:

<img width="492" alt="screen shot 2016-07-06 at 11 45 23 pm" src="https://cloud.githubusercontent.com/assets/720339/16633836/c90e94bc-43d3-11e6-8c0a-bd4d1208afca.png">

It may be not the best solution so I'd be glad to know opinion of others.

@rafibomb what do you think?

**Comment by sergeylukin** [comment]
Sorry. Of course, styles should be in `<foundation template path>/assets/scss/app.scss` in order for overrides to work properly:

``` css
@import 'settings';
$body-background: #CEDBEB;

@import
  'foundation-emails';

.Header .columns {
  padding-bottom: 0;
}

.Header .wrapper-inner {
  padding: 20px;
}

.Header .container {
  background: #CEDBEB !important;
}

.Block {
  border-width: 1px;
  border-style: solid;
  border-color: grey;
  border-radius: 5px;
  display: block !important;
}
th.columns .Block-column,
td.columns .Block-column {
  padding-top: 16px;
  padding-right: 16px !important;
  padding-bottom: 16px;
  padding-left: 16px !important;
}
@media only screen and (max-width: 596px) {
  th.columns .Block-column,
  td.columns .Block-column,
  table.body .columns .Block-column {
    padding-top: 16px;
    padding-right: 16px !important;
    padding-bottom: 16px;
    padding-left: 16px !important;
  }
}

.u-marginBn {
  margin-bottom: 0 !important;
}
```
