### ISSUE TITLE
Combine media queries

### ISSUE THREAD

**Issue by zebapy** [foundation/foundation-emails#519]
For those of us who prefer to write our media queries in the same file as the main selector, I think it'd be helpful to add something like [gulp-combine-mq](https://www.npmjs.com/package/gulp-combine-mq) to the build tools. I'd be happy to make a PR.

**Comment by rafibomb** [comment]
Are you referring to your custom CSS or the framework itself? 

For the framework it would be amazing to have related CSS all in the same file. Love the idea and a PR would really help tons of people!

This could be a great one for the next point release `v2.3`

**Comment by zebapy** [comment]
I only mean to combine media queries when embedding them into the final email

Example of separate media queries when using Sass:

`_partial.scss`

``` sass
.container {
  max-width: 600px;

  // this is usually done with a mixin
  @media (max-width: 620px) {
    max-width: 100%;
  }
}

.someColumn {
  width: 50%;
  @media (max-width: 620px) {
    width: 100%;
  }
}
```

`app.css`

``` css
.container {
  max-width: 600px;
}
@media (max-width: 620px) {
  .container {
    max-width: 100%;
  }
}

.someColumn {
  width: 50%;
}
@media (max-width: 620px) {
  .someColumn {
    width: 100%;
  }
}
```

embedded result in the email after running `npm run build`

``` html
<style>@media (max-width: 620px) { .container { max-width: 100%; } } @media (max-width: 620px) { .someColumn { width: 100%; } } </style>
```

Using something like the above mentioned `gulp-combine-mq` should solve this if it was added in the build task. 

> have related CSS all in the same file

@rafibomb I'm not sure I understand what you mean by that. I can make a PR for this but it does nothing more than merge media queries.
