### ISSUE TITLE
double margin definition in _alignment.scss

### ISSUE THREAD

**Issue by ronnidc** [foundation/foundation-emails#684]
In the scss-file `/node_modules/foundation-emails/scss/components/_alignment.scss`

There is an extra (Capitalized) `Margin: 0 auto;`

````CSS
img.float-center,
img.text-center {
  margin: 0 auto;
  Margin: 0 auto;
  float: none;
  text-align: center;
}

table,
td,
th {
  &.float-center {
    margin: 0 auto;
    Margin: 0 auto;
    float: none;
    text-align: center;
  }
}
````

It's not genrating errors to the output, it's just disturbing the debugging process a little during development. It should be an easy fix.
