### ISSUE TITLE
Don't encode ampersands in hrefs

### ISSUE THREAD

**Issue by dnglr** [foundation/foundation-emails#711]
Trying to inline an email after I put a bunch of urls with UTM query strings in it and the inliner totally botched them by changing ampersands (&) to (&amp;amp;)

Also anywhere they I manually type &amp; it changes it to &amp;amp; and same with &nbsp; changing it to &amp;nbsp;

**Comment by Creativenauts** [comment]
Here, you can use what I've created for my project. Place this yaml code in your front matter of the template you are working on.

```
# ---------------------------------------------
# UTM Tracking Parameters
# ---------------------------------------------

tracking:
    - type: "?utm_medium="
      value: "email"
    
    - type: "&utm_source="
      value: "Your Source Here"
    
    - type: "&utm_campaign="
      value: "Your Campaign Name Here"
    
    - type: "&utm_content="
      value: "Your Content Here"
```

Then place this handlebars each helper after all of your links and inliner will not encode your urchin tracking parameters.

`<a href="http://www.your-domain-here.com/{{#each tracking}}{{{this.type}}}{{{this.value}}}{{/each}}&utm_term=text-link">Your Text Link Here!</a>`
