### ISSUE TITLE
& issue

### ISSUE THREAD

**Issue by ximou94** [foundation/foundation-emails#718]
**How can we reproduce this bug?**
by inlining this code =>  `<a href="http://www.edp-audio.fr/actualites/manifestation/5188-auditionsolidarite-sous-le-feu-des-projecteurs-sur-france-5/?utm_source=newsletter-23-fevrier-2017&utm_medium=newsletter&utm_content=article-&utm_campaign=audio">Lire la suite</a>`

**Write out the HTML (or Inky code) that causes the issue.**
 `<a href="http://www.edp-audio.fr/actualites/manifestation/5188-auditionsolidarite-sous-le-feu-des-projecteurs-sur-france-5/?utm_source=newsletter-23-fevrier-2017&utm_medium=newsletter&utm_content=article-&utm_campaign=audio">Lire la suite</a>`

**What did you expect to happen?**
& convert to `&amp; `

**What happened instead?**
`&amp;amp;`

**What email clients does this happen in?**
all

**Comment by Creativenauts** [comment]
Here, you can use what I've created for my project. Place this yaml code in your front matter of the template you are working on.

```
# ---------------------------------------------
# UTM Tracking Parameters
# ---------------------------------------------

tracking:
    - type: "?utm_medium="
      value: "email"
    
    - type: "&utm_source="
      value: "Your Source Here"
    
    - type: "&utm_campaign="
      value: "Your Campaign Name Here"
    
    - type: "&utm_content="
      value: "Your Content Here"
```

Then place this handlebars each helper after all of your links and inliner will not encode your urchin tracking parameters.

`<a href="http://www.your-domain-here.com/{{#each tracking}}{{{this.type}}}{{{this.value}}}{{/each}}&utm_term=text-link">Your Text Link Here!</a>`
