### ISSUE TITLE
[Media Queries] Inline css takes precedence over media queries

### ISSUE THREAD

**Issue by ranchmed** [foundation/foundation-emails#929]
**How can we reproduce this bug?**
```css
Implement a media query in app.css such as:
.header {
    p.header__site {
        text-align: right;
        @media only screen and (max-width: #{$global-breakpoint}) {
            text-align: center;
        }
    }
}
```
Write out the HTML (or Inky code) that causes the issue.
The media query, as part of the inline process, is properly included in the \<head> tag.

**What did you expect to happen?**
Expected the media query to work - it didn't

**What happened instead?**
The inline style of "text-align: right;" took precedence, as it properly should

**What email clients does this happen in?**
Debugging in firefox

**So, What is the problem?**
The documentation for media queries does not mention the very important fact that in order for the media query to work, you must add the !import precedent modifier to the css. The following works:
```css
.header {
    p.header__site {
        text-align: right;
        @media only screen and (max-width: #{$global-breakpoint}) {
            text-align: center !important;
        }
    }
}
```
I will bet that most coders relying on the current documentation would would make this mistake and have to figure out that the issues stems from the inlining process, and not their original code! Your docs can help avoid this.
